config/routes.rb
RailsConf::Application.routes.draw do
  get "index/index"

  get "signup", { :controller => "signup", :action => "index" }
  get "signup/index"
  get "signup/approved"
  post "signup/save"
  get "admin_login", { :controller => "admin_login", :action => "index" }
  post "admin_login/login"
  get "admin_login/logout"

  resources :speakers, :conferences, :sessions, :attendees

  root :to => "index#index"

end

app/models/conference.rb
class Conference < ActiveRecord::Base
  has_many :sessions
  has_and_belongs_to_many :attendees
  scope :upcoming, lambda {
    where("scheduled_to > ?", Time.now)
  }
  scope :passed, lambda {
    where("scheduled_to < ?", Time.now)
  }
  scope :attended_by, lambda { |attendee_id|
    where("attendees_conferences.conference_id = conferences.id AND attendees_conferences.attendee_id = ?" , attendee_id)
  }
  def to_s
    name
  end
end

app/controllers/conferences_controller.rb
class ConferencesController < AdminController
  # GET /conferences
  # GET /conferences.xml
  def index
    @conferences = Conference.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @conferences }
    end
  end

  # GET /conferences/1
  # GET /conferences/1.xml
  def show
    @conference = Conference.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @conference }
    end
  end

  # GET /conferences/new
  # GET /conferences/new.xml
  def new
    @conference = Conference.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @conference }
    end
  end

  # GET /conferences/1/edit
  def edit
    @conference = Conference.find(params[:id])
  end

  # POST /conferences
  # POST /conferences.xml
  def create
    @conference = Conference.new(params[:conference])

    respond_to do |format|
      if @conference.save
        format.html { redirect_to(@conference, :notice => 'Conference was successfully created.') }
        format.xml  { render :xml => @conference, :status => :created, :location => @conference }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @conference.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /conferences/1
  # PUT /conferences/1.xml
  def update
    @conference = Conference.find(params[:id])

    respond_to do |format|
      if @conference.update_attributes(params[:conference])
        format.html { redirect_to(@conference, :notice => 'Conference was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @conference.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /conferences/1
  # DELETE /conferences/1.xml
  def destroy
    @conference = Conference.find(params[:id])
    @conference.destroy

    respond_to do |format|
      format.html { redirect_to(conferences_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/conferences_helper.rb
module ConferencesHelper
end

app/views/conferences/_form.html.erb
<%= form_for(@conference) do |f| %>
  <% if @conference.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@conference.errors.count, "error") %> prohibited this conference from being saved:</h2>

      <ul>
      <% @conference.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :scheduled_to %><br />
    <%= f.date_select :scheduled_to %>
  </div>
  <div class="field">
    <%= f.label :duration %><br />
    <%= f.text_field :duration %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/conferences/edit.html.erb
<h1>Editing conference</h1>

<%= render 'form' %>

<%= link_to 'Show', @conference %> |
<%= link_to 'Back', conferences_path %>

app/views/conferences/index.html.erb
<h1>Listing conferences</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Scheduled to</th>
    <th>Duration</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @conferences.each do |conference| %>
  <tr>
    <td><%= conference.name %></td>
    <td><%= conference.scheduled_to %></td>
    <td><%= conference.duration %></td>
    <td><%= link_to 'Show', conference %></td>
    <td><%= link_to 'Edit', edit_conference_path(conference) %></td>
    <td><%= link_to 'Destroy', conference, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Conference', new_conference_path %>

app/views/conferences/new.html.erb
<h1>New conference</h1>

<%= render 'form' %>

<%= link_to 'Back', conferences_path %>

app/views/conferences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @conference.name %>
</p>

<p>
  <b>Scheduled to:</b>
  <%= @conference.scheduled_to %>
</p>

<p>
  <b>Duration:</b>
  <%= @conference.duration %>
</p>


<%= link_to 'Edit', edit_conference_path(@conference) %> |
<%= link_to 'Back', conferences_path %>