config/routes.rb
RailsConf::Application.routes.draw do
  get "index/index"

  get "signup", { :controller => "signup", :action => "index" }
  get "signup/index"
  get "signup/approved"
  post "signup/save"
  get "admin_login", { :controller => "admin_login", :action => "index" }
  post "admin_login/login"
  get "admin_login/logout"

  resources :speakers, :conferences, :sessions, :attendees

  root :to => "index#index"

end

app/models/speaker.rb
class Speaker < ActiveRecord::Base
  has_many :sessions
  def to_s
    name
  end
end

app/controllers/speakers_controller.rb
class SpeakersController < AdminController
  # GET /speakers
  # GET /speakers.xml
  def index
    @speakers = Speaker.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @speakers }
    end
  end

  # GET /speakers/1
  # GET /speakers/1.xml
  def show
    @speaker = Speaker.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @speaker }
    end
  end

  # GET /speakers/new
  # GET /speakers/new.xml
  def new
    @speaker = Speaker.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @speaker }
    end
  end

  # GET /speakers/1/edit
  def edit
    @speaker = Speaker.find(params[:id])
  end

  # POST /speakers
  # POST /speakers.xml
  def create
    @speaker = Speaker.new(params[:speaker])

    respond_to do |format|
      if @speaker.save
        format.html { redirect_to(@speaker, :notice => 'Speaker was successfully created.') }
        format.xml  { render :xml => @speaker, :status => :created, :location => @speaker }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @speaker.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /speakers/1
  # PUT /speakers/1.xml
  def update
    @speaker = Speaker.find(params[:id])

    respond_to do |format|
      if @speaker.update_attributes(params[:speaker])
        format.html { redirect_to(@speaker, :notice => 'Speaker was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @speaker.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /speakers/1
  # DELETE /speakers/1.xml
  def destroy
    @speaker = Speaker.find(params[:id])
    @speaker.destroy

    respond_to do |format|
      format.html { redirect_to(speakers_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/speakers_helper.rb
module SpeakersHelper
end

app/views/speakers/_form.html.erb
<%= form_for(@speaker) do |f| %>
  <% if @speaker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@speaker.errors.count, "error") %> prohibited this speaker from being saved:</h2>

      <ul>
      <% @speaker.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :blog_page %><br />
    <%= f.text_field :blog_page %>
  </div>
  <div class="field">
    <%= f.label :bio %><br />
    <%= f.text_area :bio %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/speakers/edit.html.erb
<h1>Editing speaker</h1>

<%= render 'form' %>

<%= link_to 'Show', @speaker %> |
<%= link_to 'Back', speakers_path %>

app/views/speakers/index.html.erb
<h1>Listing speakers</h1>

<table>
  <tr>
    <th>Lname</th>
    <th>Fname</th>
    <th>Blog page</th>
    <th>Bio</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @speakers.each do |speaker| %>
  <tr>
    <td><%= speaker.name %></td>
    <td><%= speaker.blog_page %></td>
    <td><%= speaker.bio %></td>
    <td><%= speaker.email %></td>
    <td><%= link_to 'Show', speaker %></td>
    <td><%= link_to 'Edit', edit_speaker_path(speaker) %></td>
    <td><%= link_to 'Destroy', speaker, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Speaker', new_speaker_path %>

app/views/speakers/new.html.erb
<h1>New speaker</h1>

<%= render 'form' %>

<%= link_to 'Back', speakers_path %>

app/views/speakers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @speaker.name %>
</p>

<p>
  <b>Blog page:</b>
  <%= @speaker.blog_page %>
</p>

<p>
  <b>Bio:</b>
  <%= @speaker.bio %>
</p>

<p>
  <b>Email:</b>
  <%= @speaker.email %>
</p>


<%= link_to 'Edit', edit_speaker_path(@speaker) %> |
<%= link_to 'Back', speakers_path %>